import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import './globals.css';

const inter = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <PrimaryLayout>{children}</PrimaryLayout>
            </body>
        </html>
    );
}
